[package]
name = "png_header_scanner"
version = "0.1.0"
authors = ["Daniel Wong <drojfjord@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
walkdir = "2"
oxipng = "2.2.2"
image = "0.21.2"
